In [1]:
import numpy as np
from numpy.linalg import inv, det, eig
from sklearn.decomposition import PCA

In [2]:
v = np.array([1, 2, 3])
M = np.array([[2, 0, 1],
              [1, 3, 2],
              [0, 1, 1]], dtype=float)
print("v shape:", v.shape)
print("M shape:", M.shape)
print("M transpose:\n", M.T)
print("Matrix vector product:", M.dot(v))

v shape: (3,)
M shape: (3, 3)
M transpose:
 [[2. 1. 0.]
 [0. 3. 1.]
 [1. 2. 1.]]
Matrix vector product: [ 5. 13.  5.]


In [4]:
# Determinant and inverse
print("det(M) =", det(M))
if np.abs(det(M)) > 1e-8:
  print("inv(M):\n", inv(M))

# Eigen decomposition
vals, vecs = eig(M)
print("Eigenvalues:", vals)
print("Eigenvactors (columns):\n", vecs)

det(M) = 2.9999999999999996
inv(M):
 [[ 0.33333333  0.33333333 -1.        ]
 [-0.33333333  0.66666667 -1.        ]
 [ 0.33333333 -0.66666667  2.        ]]
Eigenvalues: [3.87938524 1.65270364 0.46791111]
Eigenvactors (columns):
 [[-0.17196417  0.92371144 -0.49926042]
 [-0.93057968 -0.20938838 -0.40700082]
 [-0.32318693 -0.32080162  0.76491134]]


In [5]:
# PCA example (using sklearn) on synthetic data
X = np.vstack([np.random.normal(loc=0, scale=1, size=(100, 2)),
               np.random.normal(loc=5, scale=0.5, size=(50,2))])
pca = PCA(n_components=2)
Xp = pca.fit_transform(X)
print("Explained variance ratio:", pca.explained_variance_ratio_)

Explained variance ratio: [0.9482433 0.0517567]


**Notes:** PCA uses eigen-decomposition of covariance matrix; the principal components are eigenvectors with largest eigenvalues.